/******************************************************************************
Finite State Machine
Project: Example
Description: Example finite state machine

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.3.4
Generation date: 2024-05-09 11:00:49 +0200
Generated from: example.dot
The finite state machine has:
  3 states
  1 transition functions
Functions and types have been generated with prefix "example_"
******************************************************************************/

#ifndef FSM_H
#define FSM_H
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef struct {
  int n;
} example_state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
  EXAMPLE_STATE_INIT = 0,  
  EXAMPLE_STATE_RUN,  
  EXAMPLE_STATE_STOP,  
  EXAMPLE_NUM_STATES,
  EXAMPLE_NO_CHANGE
} example_state_t;

// State human-readable names
extern const char *example_state_names[];

// State function and state transition prototypes
typedef example_state_t state_func_t(example_state_data_t *data);
typedef void transition_func_t(example_state_data_t *data);

// State functions

// Function to be executed in state init
// valid return states: EXAMPLE_STATE_RUN
example_state_t example_do_init(example_state_data_t *data);

// Function to be executed in state run
// valid return states: EXAMPLE_NO_CHANGE, EXAMPLE_STATE_RUN, EXAMPLE_STATE_STOP
example_state_t example_do_run(example_state_data_t *data);

// Function to be executed in state stop
// valid return states: EXAMPLE_NO_CHANGE
example_state_t example_do_stop(example_state_data_t *data);


// List of state functions
extern state_func_t *const example_state_table[EXAMPLE_NUM_STATES];


// Transition functions
void example_disable(example_state_data_t *data);

// Table of transition functions
extern transition_func_t *const example_transition_table[EXAMPLE_NUM_STATES][EXAMPLE_NUM_STATES];

// state manager
example_state_t example_run_state(example_state_t cur_state, example_state_data_t *data);

#endif
