/******************************************************************************
Finite State Machine
Project: C-CNC
Description: Finite state machine for C-CNC

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.3.4
Generation date: 2024-05-09 11:59:47 +0200
Generated from: src/fsm.dot
The finite state machine has:
  8 states
  7 transition functions
Functions and types have been generated with prefix "ccnc_"
******************************************************************************/

#include <syslog.h>
#include <termios.h>
#include "fsm.h"
#include "block.h"
#include "point.h"
#include "defines.h"


// Install signal handler: 
// SIGINT requests a transition to state stop
#include <signal.h>
static int _exit_request = 0;
static void signal_handler(int signal) {
  if (signal == SIGINT) {
    _exit_request = 1;
    syslog(LOG_WARNING, "[FSM] SIGINT transition to stop");
  }
}

static char read_key() {
  char key;
  struct termios old_tio, new_tio;
  tcgetattr(STDIN_FILENO, &old_tio);
  new_tio = old_tio;
  cfmakeraw(&new_tio);
  tcsetattr(STDIN_FILENO, TCSANOW, &new_tio);
  key = getchar();
  tcsetattr(STDIN_FILENO, TCSANOW, &old_tio);
  return key;
}

// GLOBALS
// State human-readable names
const char *ccnc_state_names[] = {"init", "idle", "stop", "load_block", "go_to_zero", "no_motion", "rapid_motion", "interp_motion"};

// List of state functions
state_func_t *const ccnc_state_table[CCNC_NUM_STATES] = {
  ccnc_do_init,          // in state init
  ccnc_do_idle,          // in state idle
  ccnc_do_stop,          // in state stop
  ccnc_do_load_block,    // in state load_block
  ccnc_do_go_to_zero,    // in state go_to_zero
  ccnc_do_no_motion,     // in state no_motion
  ccnc_do_rapid_motion,  // in state rapid_motion
  ccnc_do_interp_motion, // in state interp_motion
};

// Table of transition functions
transition_func_t *const ccnc_transition_table[CCNC_NUM_STATES][CCNC_NUM_STATES] = {
  /* states:           init             , idle             , stop             , load_block       , go_to_zero       , no_motion        , rapid_motion     , interp_motion     */
  /* init          */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* idle          */ {NULL             , NULL             , NULL             , ccnc_reset       , ccnc_begin_zero  , NULL             , NULL             , NULL             }, 
  /* stop          */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* load_block    */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , ccnc_begin_rapid , ccnc_begin_interp}, 
  /* go_to_zero    */ {NULL             , ccnc_end_zero    , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* no_motion     */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* rapid_motion  */ {NULL             , NULL             , NULL             , ccnc_end_rapid   , NULL             , NULL             , NULL             , NULL             }, 
  /* interp_motion */ {NULL             , NULL             , NULL             , ccnc_end_interp  , NULL             , NULL             , NULL             , NULL             }, 
};

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state init
// valid return states: CCNC_STATE_IDLE, CCNC_STATE_STOP
ccnc_state_t ccnc_do_init(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_STATE_IDLE;
  point_t *sp = NULL, *zero = NULL;
  signal(SIGINT, signal_handler); 
  
  syslog(LOG_INFO, "[FSM] In state init");
  
  // Steps:
  // 1. step: print out software info
  wprintf("C-CNC version %s, %s\n", VERSION, BUILD_TYPE);

  // 2. connect to the machine
  if (!data->machine) {
    data->machine = machine_new(data->ini_file);
    if (!data->machine) {
      next_state = CCNC_STATE_STOP;
      goto next_state;
    }
  }
  if (machine_connect(data->machine, NULL) != NO_ERR) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }

  // 3. load and parse G-Code file
  data->program = program_new(data->prog_file);
  if (!data->program) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }
  if (program_parse(data->program, data->machine) != NO_ERR) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }

  // 4. print parsed program
  fprintf(stderr, "Current program: %s\n", data->prog_file);
  program_print(data->program, stderr);

  // 5. sync the machine position to zero
  sp = machine_setpoint(data->machine);
  zero = machine_zero(data->machine);
  point_set_xyz(sp, point_x(zero), point_y(zero), point_z(zero));
  machine_sync(data->machine, 1);

 next_state: 
  switch (next_state) {
    case CCNC_STATE_IDLE:
    case CCNC_STATE_STOP:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from init to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state idle
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_IDLE, CCNC_STATE_LOAD_BLOCK, CCNC_STATE_STOP, CCNC_STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_idle(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  char key;

  // Steps:
  // 1. Wait for key press
  syslog(LOG_INFO, "[FSM] In state idle");
  fprintf(stderr, "Press <spacebar> to run, 'z' to zero, 'q' to quit\n");
  key = read_key();

  switch(key) {
  case ' ':
    next_state = CCNC_STATE_LOAD_BLOCK;
    break;
  case 'q':
  case 'Q':
    next_state = CCNC_STATE_STOP;
    break;
  case 'z':
  case 'Z':
    next_state = CCNC_STATE_GO_TO_ZERO;
    break;
  default:
    break;
  }

  // 2. reset timings
  data->t_tot = data->t_blk = 0.0;
  machine_sync(data->machine, 1);
  
  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_IDLE:
    case CCNC_STATE_LOAD_BLOCK:
    case CCNC_STATE_STOP:
    case CCNC_STATE_GO_TO_ZERO:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from idle to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


// Function to be executed in state stop
// valid return states: CCNC_NO_CHANGE
ccnc_state_t ccnc_do_stop(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  
  syslog(LOG_INFO, "[FSM] In state stop");
  
  // Steps:
  // 1. reset signal handler
  signal(SIGINT, SIG_DFL);

  // 2. disconnect
  wprintf("Disconnecting...\n");
  if (data->machine) {
    machine_disconnect(data->machine);
  }

  // 3. clean up resources
  wprintf("Cleaning up...\n");
  if (data->program) program_free(data->program);
  if (data->machine) machine_free(data->machine);
  wprintf("done.\n");

  
  switch (next_state) {
    case CCNC_NO_CHANGE:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from stop to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state load_block
// valid return states: CCNC_STATE_IDLE, CCNC_STATE_NO_MOTION, CCNC_STATE_RAPID_MOTION, CCNC_STATE_INTERP_MOTION
ccnc_state_t ccnc_do_load_block(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_STATE_IDLE;
  block_t *b = NULL;

  syslog(LOG_INFO, "[FSM] In state load_block");
  
  // Steps:
  // 1. get and print next block:
  b = program_next(data->program);
  if (!b) { // reached the end of program
    next_state = CCNC_STATE_IDLE;
    goto next_state;
  }
  block_print(b, stderr);

  // 2. depending on block type, select the next state
  switch (block_type(b)) {
  case NO_MOTION:
    next_state = CCNC_STATE_NO_MOTION;
    break;
  case RAPID:
    next_state = CCNC_STATE_RAPID_MOTION;
    break;
  case LINE:
  case CWA:
  case CCWA:
    next_state = CCNC_STATE_INTERP_MOTION;
    break;
  default:
    next_state = CCNC_STATE_IDLE;
    break;
  }

  // 3. Reset block time
  data->t_blk = 0.0;
  
next_state:
  switch (next_state) {
    case CCNC_STATE_IDLE:
    case CCNC_STATE_NO_MOTION:
    case CCNC_STATE_RAPID_MOTION:
    case CCNC_STATE_INTERP_MOTION:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from load_block to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state go_to_zero
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_IDLE, CCNC_STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_go_to_zero(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  
  syslog(LOG_INFO, "[FSM] In state go_to_zero");

  // Steps:
  // 1. sync with machine
  if (machine_sync(data->machine, 1) != NO_ERR) {
    _exit_request = 1;
  }

  // 2. go back to idle if setpoint has been reached
  if (machine_error(data->machine) < machine_max_error(data->machine)) {
    next_state = CCNC_STATE_IDLE;
  }

  // 3. CTRL-C may be used to skipping over a rapid block
  if (_exit_request) {
    _exit_request = 0;
    next_state = CCNC_STATE_IDLE;
  }
  
  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_IDLE:
    case CCNC_STATE_GO_TO_ZERO:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from go_to_zero to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


// Function to be executed in state no_motion
// valid return states: CCNC_STATE_LOAD_BLOCK
ccnc_state_t ccnc_do_no_motion(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_STATE_LOAD_BLOCK;
  
  syslog(LOG_INFO, "[FSM] In state no_motion");

  // Steps:
  // 1. print block number
  fprintf(stderr, "No motion block %zu\n", block_n(program_current(data->program)));

  // 2. increment total time
  data->t_tot += machine_tq(data->machine);
  
  switch (next_state) {
    case CCNC_STATE_LOAD_BLOCK:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from no_motion to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state rapid_motion
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_LOAD_BLOCK, CCNC_STATE_RAPID_MOTION
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_rapid_motion(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  block_t *b = program_current(data->program);
  point_t *pos = machine_position(data->machine);

  syslog(LOG_INFO, "[FSM] In state rapid_motion");

  // Steps:
  // 1. synch the machine
  machine_sync(data->machine, 1);

  // 2. exit state if error is small
  if (machine_error(data->machine) < machine_max_error(data->machine)) {
    next_state = CCNC_STATE_LOAD_BLOCK;
  }

  // 3. CTLR-C
  if (_exit_request) {
    _exit_request = 0;
    next_state = CCNC_STATE_LOAD_BLOCK;
  } 

  // 4. print position table
  printf("%lu %d %f %f %f %f %f %f %f %f\n", block_n(b), block_type(b), data->t_tot, data->t_blk, 0.0, 0.0, 0.0, point_x(pos), point_y(pos), point_z(pos));

  // 5. increment times
  data->t_blk += machine_tq(data->machine);
  data->t_tot += machine_tq(data->machine);
  
  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_LOAD_BLOCK:
    case CCNC_STATE_RAPID_MOTION:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from rapid_motion to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


// Function to be executed in state interp_motion
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_LOAD_BLOCK, CCNC_STATE_INTERP_MOTION
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_interp_motion(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  data_t lambda, feedrate;
  point_t *sp = NULL;
  block_t *b = program_current(data->program);

  syslog(LOG_INFO, "[FSM] In state interp_motion");

  // Steps:
  // 1. calculate lambda and intepolate
  sp = block_interpolate_t(b, data->t_blk, &lambda, &feedrate);

  // 2. print position table
  printf("%lu %d %f %f %f %f %f %f %f %f\n", block_n(b), block_type(b), data->t_tot, data->t_blk, lambda, lambda * block_length(b), feedrate, point_x(sp), point_y(sp), point_z(sp));

  // 3. Sync machine
  machine_sync(data->machine, 0);

  // 4. check if block is done
  if (data->t_blk >= block_dt(b) + machine_tq(data->machine) / 10.0) {
    next_state = CCNC_STATE_LOAD_BLOCK;
  }

  // 6. increment times
  data->t_blk += machine_tq(data->machine);
  data->t_tot += machine_tq(data->machine);
  
  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_LOAD_BLOCK:
    case CCNC_STATE_INTERP_MOTION:
      break;
    default:
      syslog(LOG_WARNING, "[FSM] Cannot pass from interp_motion to %s, remaining in this state", ccnc_state_names[next_state]);
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */    
                                         
// This function is called in 1 transition:
// 1. from idle to load_block
void ccnc_reset(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_reset");
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from idle to go_to_zero
void ccnc_begin_zero(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_begin_zero");
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from load_block to rapid_motion
void ccnc_begin_rapid(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_begin_rapid");
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
void ccnc_begin_interp(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_begin_interp");
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from rapid_motion to load_block
void ccnc_end_rapid(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_end_rapid");
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from interp_motion to load_block
void ccnc_end_interp(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_end_interp");
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from go_to_zero to idle
void ccnc_end_zero(ccnc_state_data_t *data) {
  syslog(LOG_INFO, "[FSM] State transition ccnc_end_zero");
  /* Your Code Here */
}


/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

ccnc_state_t ccnc_run_state(ccnc_state_t cur_state, ccnc_state_data_t *data) {
  ccnc_state_t new_state = ccnc_state_table[cur_state](data);
  if (new_state == CCNC_NO_CHANGE) new_state = cur_state;
  transition_func_t *transition = ccnc_transition_table[cur_state][new_state];
  if (transition)
    transition(data);
  return new_state;
};

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
  ccnc_state_t cur_state = CCNC_STATE_INIT;
  openlog("SM", LOG_PID | LOG_PERROR, LOG_USER);
  syslog(LOG_INFO, "Starting SM");
  do {
    cur_state = ccnc_run_state(cur_state, NULL);
    sleep(1);
  } while (cur_state != CCNC_STATE_STOP);
  ccnc_run_state(cur_state, NULL);
  return 0;
}
#endif
